### ISSUE TITLE
"Unhanded exception" - If it's because I have it opened as admin just close or type "." as comment

### ISSUE THREAD

**Issue by DraGZ76** [Jorixon/JASM#92] opened 2023-11-25 14:40 UTC
System.Runtime.InteropServices.COMException (0x8001010E)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Interop.WinRTNotifyCollectionChangedEventArgsRuntimeClassFactory.CreateInstanceWithAllParameters(NotifyCollectionChangedAction action, IList newItems, IList oldItems, Int32 newIndex, Int32 oldIndex)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventArgs.CreateMarshaler2(NotifyCollectionChangedEventArgs value)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at GIMI_ModManager.WinUI.ViewModels.CharactersViewModel.<OnNavigatedTo>b__50_0()
   at GIMI_ModManager.WinUI.ViewModels.CharactersViewModel.OnNavigatedTo(Object parameter)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by Jorixon** [comment] 2023-11-25 17:29
Can't say i fully understand the title here. However, I think I know what the issue is.

First thing you can try to do is delete/rename the `ModNotifications.json` file at `C:\Users\<username>\AppData\Local\JASM\` `ApplicationData_Genshin` or `ApplicationData_Honkai` folder. This will clear all update notifications for mods

If that does not work, you can also try to rename `ApplicationData_Genshin` to `ApplicationData_Genshin_backup` and start jasm again. This will reset your personal settings for jasm. Mod specific data is stored in the mods themselves.

**Comment by DraGZ76** [comment] 2023-11-25 18:07
All right thanks

**Comment by Jorixon** [comment] 2023-11-27 21:04
Did my suggestion work? Can I close this issue?

**Comment by DraGZ76** [comment] 2023-11-27 21:27
> Hi, did my suggestion work? Can I close this issue?

Oh yeah sorry I forgot

**Closed** 2023-11-27 21:51 UTC
